### ISSUE TITLE
npm start only works once

### ISSUE THREAD

**Issue by jkoervers** [rothsandro/angular-library-example#1]
I created a library using your guide (https://sandroroth.com/blog/angular-library). Btw, your guide is great! Everything worked fine until using `npm start` which results in:

```
Error: projects/showcase/src/app/app.component.html:4:1 - error NG8001: 'lib-ui-sdk' is not a known element:
1. If 'lib-ui-sdk' is an Angular component, then verify that it is part of this module.
2. If 'lib-ui-sdk' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```
...

So, I cloned your repo and running `npm start` worked, but only once. Afterwards I got the same error. (I canceled the command using ctrl+c.)

Running `ng build @mycomp/ui-sdk --watch --configuration development` in one console and `ng serve showcase` in another console works for me. When I change the background color of the button in the library, the color changes in the browser.

**Comment by jkoervers** [comment]
I now changed the script to use rimraf to delete the dist folder before building.

```
"clean": "rimraf dist",
"start": "npm run clean && run-p lib:watch showcase:start-waiton",
```

**Comment by rothsandro** [comment]
@jkoervers Thanks for reporting this, it's fixed.
