### ISSUE TITLE
How to define and export assets (.js) / global styles from an entry point?

### ISSUE THREAD

**Issue by akcasoy** [rothsandro/angular-library-example#3]
Hi Sandro! We find your article "Building an Angular Library with multiple entry points" incredibly useful, and have just restructured our project. 

I actually wanted to submit a feature request / a suggestion, maybe you can also add some help about assets. We have some js files, which have to be defined in parent angular applications' angular.json as scripts. Entry points should be able to define some js files, which then will be exported and can be used from the parent applications. 

CSS ist also another important asset. Local styles, which you can define in components' css file works of course automatically, but if a component in an entry point needs some global styles (which we define in styles.css in parent app), it would also be so nice that if entry points could export their own global styles, which then automatically merged into the parent's styles.css.

We appreciate your help so far with the articel, and hope you can expand it a bit regarding those aspects.

**Comment by rothsandro** [comment]
You can add static assets like styling to your `ng-package.json` file and export them:

```scss
// projects/mycomp/ui-sdk/styles/global.scss
body {
  background: red
}
```

```json5
// projects/mycomp/ui-sdk/ng-package.json
{
  "assets": ["styles/**/*.scss"],
  // ...
}
```

```json5
// projects/mycomp/ui-sdk/package.json
{
  "exports": {
    "./global": {
      "sass": "./styles/global.scss"
    }
  }
}
```

When importing the library via npm package this should already work. For the showcase app in the same workspace it's not that easy unfortunately. You can of course provide the relative path to the dist folder and import the SCSS file from there, but using the package name doesn't work, see https://github.com/angular/angular-cli/issues/23552

**Comment by akcasoy** [comment]
Unfortunately we cannot export styles from subentry-points, and their own ng-package.json.
It would be very nice to have individual scss files in subfolders (like your i18n), instead of a one giant css file.

**Comment by rothsandro** [comment]
It looks like the `assets` property is ignored on subentry points but you can still export multiple SCSS files from both, the main entry point and any subentry point by defining them in the central `ng-package.json` file. 

```json5
// projects/mycomp/ui-sdk/ng-package.json
{
  "assets": [
    {
      "glob": "button.scss",
      "input": "button/src/",
      "output": "button/"
    },
  ]
}
```

```json5
{
  "exports": {
    "./button": {
      "sass": "./button/button.scss"
    }
  }
}
```

And then in your app:

```scss
// styles.scss
@import "@mycomp/ui-sdk/button";
```
