### ISSUE TITLE
Angular 17 lib with standalone components

### ISSUE THREAD

**Issue by richieracoon** [rothsandro/angular-library-example#4]
I tried to replicate your library using angular 17, but when I export the members I get the same error over and over: 
the newly created component wasn't found but the others the library has been created with can be found and are exported. 

Component not working:
import { Component } from '@angular/core';

@Component({
  selector: 'appkit-mobile-button',
  standalone: true,
  imports: [],
  exportAs: 'AppkitMobileButtonComponent',
  template: `
    <p>
      appkit-mobile-button works!
    </p>
  `,
  styles: ``
})
export class AppkitMobileButtonComponent {

}

Component working:

import { Component } from '@angular/core';

@Component({
  selector: 'lib-appkit-mobile',
  standalone: true,
  imports: [],
  exportAs: 'AppkitMobileComponent',
  template: `
    <p>
      appkit-mobile works!
    </p>
  `,
  styles: ``
})
export class AppkitMobileComponent {

}

public-api.ts:
/*
 * Public API Surface of appkit-mobile
 */

export * from './lib/appkit-mobile.service';
export * from './lib/appkit-mobile.component';
export * from './lib/appkit-mobile-button.component';

Error: 
Error: export 'AppkitMobileButtonComponent' (imported as 'AppkitMobileButtonComponent') was not found in '@xyz/appkit-mobile' (possible exports: AppkitMobileComponent, AppkitMobileService)

**Comment by rothsandro** [comment]
Can you share a repository?

**Comment by richieracoon** [comment]
Actually I think this issue could be closed or deleted, because it's been a caching problem. In my test project the node_modules been cached in the .angular directory and therefore not been updated accordingly.

**Comment by richieracoon** [comment]
Actually I think this issue could be closed or deleted, because it's been a caching problem. In my test project the node_modules been cached in the .angular directory and therefore not been updated accordingly.
