### ISSUE TITLE
Unknown html tag

### ISSUE THREAD

**Issue by lpagliar** [rothsandro/angular-library-example#6]
Thanks for the wonderful guide, I was able to use a component lib via npm link.

The only problem I have left to resolve is that my IntelliJ IDE doesn't recognize the component tag, 
"Unknown html tag lib-button".
Did I forget to make any declarations?

**Comment by rothsandro** [comment]
Hard to say without a repro. I'm not a IntelliJ user and my guide is for VSCode, but I tested it very briefly with the IntelliJ demo and it works for me (though auto imports don't work properly). Does it work for you in VSCode?

**Comment by lpagliar** [comment]
Thanks @rothsandro for the prompt reply, it works with VS Code, it's an intellij problem that doesn't import correctly.
VSCode works fine
